function metas = parse_rwc(rwc_folder)
subfolder_dict = ...
    {'Ba','Bo','Cl','Co','Fh','Fl','Ob','Pn','Sa','Ta','Tb','Tr','Va','Vl'};
symbol_dict = { ...
    'as', 'Alto Saxophone' ; ...
    'cb', 'Double Bass';
    'cl', 'Clarinet' ; ...
    'fg', 'Bassoon' ; ...
    'fl', 'Flute' ; ...
    'hr', 'French Horn' ; ...
    'ob', 'Oboe' ; ...
    'pf', 'Piano' ; ...
    'ss', 'Soprano Saxophone' ; ...
    'tu', 'Tuba' ; ...
    'tb', 'Trombone' ; ...
    'tr', 'Trumpet' ; ...
    'ts', 'Tenor Saxophone' ; ...
    'vc', 'Cello' ; ...
    'vl', 'Viola' ; ...
    'vn', 'Violin'};

nSubfolders = length(subfolder_dict);
metas = cell(nSubfolders,1);
wav_handle = @(x) length(x)>5 && strcmp(x((end-3):end),'.wav');

for subfolder_index = 1:nSubfolders
    subfolder = subfolder_dict{subfolder_index};
    subfolder_path = fullfile(rwc_folder,subfolder);
    file_infos = dir(subfolder_path);
    file_names = {file_infos.name};
    wavfile_bools = cellfun(wav_handle,file_names);
    wavfile_names = file_names(wavfile_bools);
    nWavfiles = length(wavfile_names);
    metas{subfolder_index}(1:nWavfiles) = struct( ...
        'instrument_id', [], ...
        'style_id', [], ...
        'pitch_id', [], ...
        'nuance_id', [], ...
        'batch_id', [], ...
        'instrument_symbol', [], ...
        'instrument_name', [], ...
        'nuance', [], ...
        'subfolder', [], ...
        'batch', [], ...
        'wavfile_name', []);
    for wavfile_index = 1:nWavfiles
        meta = metas{subfolder_index}(wavfile_index);
        wavfile_name = wavfile_names{wavfile_index};
        underscore_position = strfind(wavfile_name,'_');
        prefix = wavfile_name(1:(underscore_position-1));
        postfix = wavfile_name((underscore_position+1):end);
        
        prefix_scanner = textscan(prefix,'%d%s');
        meta.batch = prefix_scanner{1};
        meta.style_id = mod(meta.batch, 10);
        infix_string = prefix_scanner{2}{1};
        n_position = strfind(infix_string,'no');
        o_position = n_position + 1;
        meta.instrument_symbol = infix_string(1:(n_position-1));
        meta.instrument_id = ...
            find(strcmp(symbol_dict(:,1),meta.instrument_symbol));
        meta.instrument_name = symbol_dict{meta.instrument_id,2};
        meta.nuance = infix_string(o_position+1:end);
        switch meta.nuance
            case 'p'
                meta.nuance_id = 1;
            case 'm'
                meta.nuance_id = 2;
            case 'f'
                meta.nuance_id = 3;
        end
        postfix_scanner = textscan(postfix,'%d.wav');
        meta.pitch_id = postfix_scanner{1};
        meta.subfolder = subfolder;
        meta.wavfile_name = wavfile_name;
        metas{subfolder_index}(wavfile_index) = meta;
    end
end
metas = [metas{:}];
batches = [metas.batch];
unique_batches = unique(batches);
for batch_id = 1:length(unique_batches)
    batch = unique_batches(batch_id);
    [metas([metas.batch] == batch).batch_id] = deal(batch_id);
end
end